INSERT INTO TB_USERS (NAME, EMAIL, PASSWORD) VALUES ('Bob', 'bob@gmail.com', '$2a$10$p0BOVpqwhtAYqc2eUvTHZONTtkBqEkLVvkzvMQdcGvmPzBg4C0AOm');
INSERT INTO TB_USERS (NAME, EMAIL, PASSWORD) VALUES ('Ray', 'ray@gmail.com', '$2a$10$X8bjkScYv2rqT04nfibvj.pmwueevGym9.RauqqEy3Fmv6IehePH6');
INSERT INTO TB_USERS (NAME, EMAIL, PASSWORD) VALUES ('Chris', 'chris@gmail.com', '$2a$10$D1ZJTMVjCkWCuTQt4UvgteVUkNUAMQIuVLgk6GnDDw4D3LYo2Hhba');

INSERT INTO TB_ROLES (ROLE_NAME) VALUES ('ROLE_OPERATOR');
INSERT INTO TB_ROLES (ROLE_NAME) VALUES ('ROLE_ADM');

INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
